spring:
  application:
    name: Dallyeobom
  profiles:
    include:
      - database
      - oauth
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
  cloud:
    compatibility-verifier:
      enabled: false
  threads:
    virtual:
      enabled: true

server:
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
management:
  server:
    port: 8888
  endpoints:
    web:
      exposure:
        include: httpexchanges

springdoc:
  swagger-ui:
    tagsSorter: alpha
    enabled: true
  api-docs:
    path: /api-docs
