spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 5 # DB 최대 세션수가 30개인데 서버배포시 rolling update를 할때 디폴트 값인 10개씩 먹으면 아슬아슬해서 줄였습니다!
logging:
  level:
    org:
      hibernate: info
